// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asp2.DbContexts;

#nullable disable

namespace asp2.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20250203015216_InitialDataSeed")]
    partial class InitialDataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("asp2.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Heart of Mainland",
                            Name = "Yaba"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Wizkid's Home",
                            Name = "Surulere"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The business center of Lagos",
                            Name = "Ikeja"
                        });
                });

            modelBuilder.Entity("asp2.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfInterest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "Main University in Lagos",
                            Name = "Unilag"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "A staple",
                            Name = "Under-Bridge"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "The place with the roundabout",
                            Name = "Masha"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "known for its bus-stop",
                            Name = "Itire"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "Has many factories",
                            Name = "idk Road"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "Full of Churches",
                            Name = " Another Road"
                        });
                });

            modelBuilder.Entity("asp2.Entities.PointOfInterest", b =>
                {
                    b.HasOne("asp2.Entities.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("asp2.Entities.City", b =>
                {
                    b.Navigation("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
